In [1]:
import json
import pandas as pd
import numpy as np
import random
from bidict import bidict
import pickle
import tensorflow as tf

In [2]:
with open("../../data/datasets/title_seq.json", "r") as f:
    data = json.load(f)

In [3]:
print(len(data["train_data"]))
print(len(data["test_data"]))

80781
20195


In [4]:
seqs = np.random.randint(low=3, size=(5,3))

In [10]:
title_seq = tf.placeholder(tf.int32, [5, 3])
embeddings = tf.Variable(tf.eye(3), trainable=False)

title_emb_input = tf.nn.embedding_lookup(embeddings, title_seq)
max_arg = tf.argmax(title_emb_input, 2)

In [8]:
seqs.shape

(5, 3)

In [11]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    embs, argsm = sess.run([title_emb_input, max_arg], {title_seq: seqs})

In [13]:
argsm

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 0],
       [0, 0, 2],
       [1, 2, 1]])

In [15]:
seqs

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 0],
       [0, 0, 2],
       [1, 2, 1]])

In [38]:
seqs[0]

array([2, 1, 0])

In [42]:
seqs[0][1:] = [3,4]

In [43]:
seqs

array([[2, 3, 4],
       [1, 1, 0],
       [1, 1, 0],
       [2, 2, 1],
       [2, 1, 0]])

In [45]:
seqs[0][1:]

array([3, 4])